### ISSUE TITLE
How can I transform the txt-file?

### ISSUE THREAD

**Issue by getengqing** [pannous/caffe-ocr#4]
The project use caffe compute, but how can I transform the txt-file to cv-data?
Check failed: cv_img.data Could not load training_images/G/TimesNewRoman-7-4.png 16

**Comment by Mezzano** [comment]
Same here:
Check failed: cv_img.data Could not load training_images/1/TimesNewRoman-10-4.png

**Comment by ncaadam** [comment]
I'm having the same issue. Looks like we're missing training data.

**Comment by Bleyddyn** [comment]
I created a pull request that deletes the missing files from the test and training index files. I don't know how active this project is, but the fix is easy to do manually if the pull request doesn't get merged in.

**Comment by twmht** [comment]
I have the same issue.

**Comment by pannous** [comment]
thanks for the pull request #5
